---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.yml
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- dist/
- node_modules/
